@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Mar 12 13:44:08 +0100 2026
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim attention_output_behav -key {Behavioral:sim_1:Functional:attention_output} -tclbatch attention_output.tcl -protoinst "protoinst_files/bd_6e42.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/Ahmed/Desktop/MedEdge-Transformer/FPGA/Transformer/Transformer/qkv_projector_behav.wcfg -log simulate.log"
call xsim  attention_output_behav -key {Behavioral:sim_1:Functional:attention_output} -tclbatch attention_output.tcl -protoinst "protoinst_files/bd_6e42.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/Ahmed/Desktop/MedEdge-Transformer/FPGA/Transformer/Transformer/qkv_projector_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
